### ISSUE TITLE
No CONTRIBUTING.md File available

### ISSUE THREAD

**Issue by sunkusaarthak** [fikrihkll/android_speedealer#11]
Create a CONTRIBUTING.md File

**Comment by sunkusaarthak** [comment]
Can i Help you to create a CONTRIBUTING.md file

**Comment by fikrihkll** [comment]
> Can i Help you to create a CONTRIBUTING.md file

Sure bro, go for it!

**Comment by sunkusaarthak** [comment]
why you have closed the issue

**Comment by sunkusaarthak** [comment]
Successfully Created the contributing.md file 
merge the pull request.
